[package]
name = "asd"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

#To add many folder define a workspace adding members to members array
[workspace]
members=["sorting"]
